
version: '3.7'
services:
  website:
    image: php:7.2-apache
    depends_on:
      - api
    environment:
      - USERNAME=toto
      - PASSWORD=python
    volumes:
      - ./website/:/var/www/html/
    ports:
      - 80:80
    networks:
      - api_network
  api:
    image: kra:v1
    ports:
      - 5000:5000
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - api_network
networks:
  api_network:
